/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;
static IconData returnIcon(String name){
  if(name == 'magnit')
  return magnit;
  if(name == 'fix_price')
    return fix_price;
  if(name == 'seven_eleven')
    return seven_eleven;
  if(name == 'tabris')
    return tabris;
  if(name == 'pyatorochka')
    return pyatorochka;
  return pyatorochka;
}
  static const IconData magnit = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fix_price = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seven_eleven = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tabris = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pyatorochka = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
